require:
  - rubocop-graphql
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - config.ru
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/assets.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb
    - config/initializers/airbrake.rb
    - config/initializers/application_controller_renderer.rb
    - config/initializers/assets.rb
    - config/initializers/backtrace_silencers.rb
    - config/initializers/content_security_policy.rb
    - config/initializers/cookies_serializer.rb
    - config/initializers/devise.rb
    - config/initializers/filter_parameter_logging.rb
    - config/initializers/inflections.rb
    - config/initializers/mime_types.rb
    - config/initializers/rack_attack.rb
    - config/initializers/wrap_parameters.rb
    - config/puma.rb
    - config/spring.rb
    - db/schema.rb
    - db/seeds/**/*
    - Gemfile.lock
    - script/rails
    - vendor/**/*

  NewCops: enable

Capybara/SpecificFinders:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Naming/MethodParameterName:
  AllowedNames:
    - el
    - id
    - lr

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails:
  Enabled: true

Rails/ActionOrder:
  ExpectedOrder:
    - create
    - destroy
    - edit
    - index
    - new
    - show
    - update

Rails/HttpStatus:
  EnforcedStyle: numeric

RSpec/AnyInstance:
  Enabled: false

RSpec/BeNil:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MatchArray:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 15

Style/NegatedIf:
  EnforcedStyle: postfix

RSpec/NestedGroups:
  Max: 10

RSpec/Rails/HaveHttpStatus:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '()'
    '%i': '[]'
    '%I': '[]'
    '%r': '()'
    '%w': '[]'
    '%W': '[]'

Style/PerlBackrefs:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
