#!/bin/sh

sublime &
gnome-terminal &
google-chrome &
xscreensaver -nosplash &
numlockx on &

sudo xrandr --output VGA1 --mode 1440x900 --output HDMI1 --mode 1440x900 --left-of VGA1
amixer set Master 90% unmute
amixer set PCM 85% unmute

which fbautostart > /dev/null

if [ $? -eq 0 ]; then
  fbautostart
fi

exec fluxbox
