# ENVIRONMENT
  #export JAVA_HOME=~/Library/Java/JavaVirtualMachines/1.7.0.jdk/Contents/Home
  export ANT_HOME=/Users/$USER/Development/apache-ant-1.8.2
  export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home
  export JBOSS_HOME=/Users/$USER/Development/jboss-5.1.0.GA
  export JETTY_HOME=/Users/$USER/Development/jetty-6.1.3
  export JRUBY_HOME=/Library/Frameworks/JRuby.framework/Versions/Current
  export M2_HOME=/Users/$USER/Development/apache-maven-3.0.3
  export MACPORTS=/opt/local/bin:/opt/local/sbin
  export MONGO_HOME=/usr/local/mongodb
  export MYSQL_HOME=/usr/local/mysql-5.1.42-osx10.5-x86_64
  export RABBIT_MQ=/usr/local/sbin
  export TOMCAT_HOME=/Users/$USER/Development/apache-tomcat-7.0.23

  export PATH=$PATH:$ANT_HOME/bin:$JAVA_HOME/bin:$JBOSS_HOME/bin:$JETTY_HOME/bin:$JRUBY_HOME/bin:$M2_HOME/bin:$MACPORTS:$MONGO_HOME/bin:$MYSQL_HOME/bin:$RABBIT_MQ:$TOMCAT_HOME/bin

  export REPO=/Users/$USER/.m2/repository
  export EDITOR='/usr/local/bin/sublime'
  export GIT_EDITOR='/usr/local/bin/sublime'

# RUBY
  source ~/.rvm/scripts/rvm

# ALIAS
  alias .='cd .'
  alias ..='cd ..'
  alias ...='cd ../../'
  alias bashclear='echo "" > ~/.bash_history'
  alias cls='clear'
  alias folders='ls -Gal | grep ^d'
  alias ip='curl ifconfig.me'
  alias kill='kill -9'
  alias la='ls -lah'
  alias ps='ps aux | grep'
  alias psjava='jps -l'
  alias reload='source ~/.bash_profile'
  alias speedup='sudo find /private/var/log/asl/* -mtime +5 -exec rm -rf {} \;'
  alias upgrade='sudo apt-get update && sudo apt-get upgrade && sudo apt-get clean'
  alias work='cd ~/workspace'
  alias ec2='ssh -i'

  alias jbossstart='$JBOSS_HOME/bin/run.sh'
  alias jbossstop='$JBOSS_HOME/bin/shutdown.sh -S'

  alias mysqlrestart='sudo /Library/StartupItems/MySQLCOM/MySQLCOM restart'
  alias mysqlstart='sudo /Library/StartupItems/MySQLCOM/MySQLCOM start'
  alias mysqlstop='sudo /Library/StartupItems/MySQLCOM/MySQLCOM stop'

  alias tomcatclear='rm $TOMCAT_HOME/logs/*.log'
  alias tomcatstart='sudo $TOMCAT_HOME/bin/shutdown.sh'
  alias tomcatstop='sudo $TOMCAT_HOME/bin/startup.sh'

  ## MONGODB
  alias mongoconn='$MONGO_HOME/bin/mongo'
  alias mongostart='$MONGO_HOME/bin/mongod --dbpath $MONGO_HOME/data/db'

  ## GIT
  alias clone='git clone'
  alias gc='git commit'
  alias gg='gitg &'
  alias gk='git checkout'
  alias gl="git log --pretty=format:'%Cred%h%Creset%C(yellow)%d%Creset %s %Cgreen(%cr) %C(cyan  )<%an>%Creset' --abbrev-commit"
  alias gs='git status -sb'
  alias master='git checkout master'
  alias pull='git pull'
  alias push='git push; git push --tags'

  function gp() {
    git commit $1 -m $2 --author="Daniel Faria <danielfariati@gmail.com>"
  }

  function ec2() {
    ssh -i "~/.ssh/$1.pem" "ubuntu@$2"
  }

  ## MKV
  alias mkv='~/Development/mkvdts2ac3.sh -f -i -n -d -c English --new ~/mkv.mkv'

  ## RUBY
  alias be='bundle exec'
  alias bi='bundle install'
  alias bu='bundle update'
  alias cucumber='bundle exec cucumber feature'
  alias migrate='rake db:drop:all; rake db:create:all; rake db:migrate; rake db:setup; rake db:test:prepare'
  alias rc='rails c'
  alias rs='rails s'
  alias rsp='rails s -p 3001'
  alias rspec='bundle exec rspec'
  alias spec='bundle exec rspec spec'

# COLOR
  export CLICOLOR=1
  export GREP_COLOR='1;37'
  export GREP_OPTIONS='--color=auto'
  export LSCOLORS=ExFxCxDxBxegedabagacad

  # 30: Black | 31: Red | 32: Green | 33: Yellow | 34: Blue | 35: Purple | 36: Cyan | 37: White | green others...
  # 0: Normal | 1: Bold
  function prompt() {
    local CYAN='\[\033[0;36m\]'
    local PURPLE='\[\033[0;35m\]'
    local RED='\[\033[0;31m\]'
    local WHITE='\[\033[0;37m\]'
    local YELLOW='\[\033[0;33m\]'

    export PS1="$WHITE\u$RED@$PURPLE\h $CYAN\w $WHITE(`~/.rvm/bin/rvm-prompt v`) \$(parse_git_branch) $YELLOW$ \[\e[m\]\[\e[m\]"
  }; prompt

  parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
  }
