#!/bin/bash

export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/wbotelhos/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"

docker-machine env default

docker_up() {
  docker-machine start default &&
  docker-machine env default &&
  eval "$(docker-machine env default)" &&
  docker-compose start
}
