#!/bin/bash

eval "$(docker-machine env default)"

export DOCKER_CERT_PATH='/Users/wbotelhos/.docker/machine/machines/default'
export DOCKER_HOST='tcp://192.168.99.100:2376'
export DOCKER_MACHINE_NAME='default'
export DOCKER_TLS_VERIFY='1'
